
<style>
         .caixa-chat {
            box-sizing: border-box;
            display: flex;
            overflow-y: scroll;
            padding: 10px 15px;
            width: 100%;
            max-height: 300px;
            scroll-snap-type: y mandatory;
            scroll-padding: 10px;
            border-radius: 8px;
            gap: 12px;
            scroll-behavior: smooth;
         }
         .caixa-chat::-webkit-scrollbar {
            width: 6px; 
            height: 10px;              
         }

         .caixa-chat::-webkit-scrollbar-track {
            background: transparent;        
         }

         .caixa-chat::-webkit-scrollbar-thumb {
            background-color: #4311A4;    
            border-radius: 20px;       
            border: none;  
         }
         .chat {
            margin: 8px 0px;
         }
         .chat p {
            max-width: 70%;
            padding: 8px !important;                           
            border-radius: 15px;
            font-size: 13px !important;
            line-height: 18px !important;
         }
         .chat-comprador p {
            background: #004AAD;
            color: #FFF !important;

         }
         .chat-offer p {
            text-align: end;
            background: #7ED957;
            color: #000 !important;
         }
         .chat span {
            font-size: 9px !important;
         }
         .caixa-enviar {
            position: relative;
         }
         .botao-wpp {
            position: absolute;
            right: 0;
            top: 8px;
         }
         .icon-wpp {            
            background-color: #FFF;
            padding: 7px;
         }
</style>

      <section>
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-12">
                  <div class="faq-content">
                  

                     <?php if(isset($this->view->mensagens) && !empty($this->view->mensagens)) {
                        foreach($this->view->mensagens as $key => $contato) {
                        ?>
                     

                        <div class="faq-accordion accord-faq<?= $key+1 ?>">
                           <button class="accordion accord<?= $key+1 ?>">
                           <?= $contato['nome_contato'] ?> - <?= $contato['telefone'] ?>
                           </button>
                           <div class="panel fadeinleft"  style="height: 350px;">
                              <div class="caixa-chat d-flex">

                                 <div class="d-block w-100">

                                    <?php foreach($contato['mensagens'] as $mensagem) {?>

                                       <?php if($mensagem['por_offer'] == false) {?>

                                          <div class="chat chat-comprador d-flex justify-content-start">
                                             <p class="text-white"><?= $mensagem['mensagem'] ?> <span>
                                                <?php 
                                                   $date = date_create($mensagem['data_hora']);
                                                   echo date_format($date, 'H:i');
                                                ?>
                                             </span></p>
                                          </div>

                                       <?php } ?> 

                                       <?php if($mensagem['por_offer'] == true) {?>

                                          <div class="chat chat-offer d-flex justify-content-end">
                                             <p class="text-white"><?= $mensagem['mensagem'] ?> <span>
                                                <?php 
                                                   $date = date_create($mensagem['data_hora']);
                                                   echo date_format($date, 'H:i');
                                                ?>
                                             </span></p>
                                          </div>

                                       <?php } ?>

                                    <?php } ?>

                                 </div>

                              </div>  
                                 
                                 <div class="mt-1 pt-1" style="border-top: 2px solid #4311A4;">
                                    <form action="/enviar_mensagem?telefone=<?= $contato['telefone'] ?>&&nome=<?= htmlspecialchars($contato['nome_contato'], ENT_QUOTES, 'UTF-8') ?>" method="post">
                                       <div class="d-flex justify-content-center w-100">
                                          <div class="w-100 caixa-enviar">
                                             <input class="form-control" type="text" name="mensagem" id="mensagem">
                                             <button class="botao-wpp" type="submit" style="border: none; background: none;"><i class="ti-search icon-wpp"></i></button>
                                          </div>
                                       </div>
                                    </form>
                                 </div>

                              
                           </div>
                        </div>


                     <?php }} ?>

                  </div>
               </div>
            </div>
         </div>
      </section>