<!--NO HTML--><!--NO HTML--><!--NO HTML--><!--NO HTML--><!--NO HTML--><!--NO HTML-->
<?php

use MF\Model\Container;

 if($this->view->total_paginas > 1) {?>

<ul class="pagination">
   <?php if(isset($_GET['page']) && $_GET['page'] > 1) {?>

   <li class="pageNumber">
      <a href="/meus_produtos" class="prev">
         <p
            class="ti-angle-double-left"></p>
      </a>
   </li>

   <?php } ?>

   <?php 

      $pagina_atual = $this->view->pagina_atual;
      $range = $this->view->range_paginas;
      $inicio = max($pagina_atual - $range, 1);
      $final = min($pagina_atual + $range, $this->view->total_paginas);

      for($i = $inicio; $i <= $final; $i++) {

   ?>

   <li class="pageNumber <?php if($i == $pagina_atual) {?> active <?php } ?>">
      <a href="/meus_produtos?page=<?= $i ?>">
         <p><?= $i ?></p>
      </a>
   </li>

   <?php } ?>
   

   <?php if(!isset($_GET['page']) || $_GET['page'] != $this->view->total_paginas) {?>
   <li class="pageNumber">
      <a href="/meus_produtos?page=<?= $this->view->total_paginas ?>" class="next">
         <p
            class="ti-angle-double-right"></p>
      </a>
   </li>
   <?php } ?>
</ul>

<?php } ?>
<!--NO HTML--><!--NO HTML--><!--NO HTML--><!--NO HTML--><!--NO HTML--><!--NO HTML-->

<!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER-->
<?php

      $produtos = Container::getModel('Produto');
		//total de registros
		$total_registros = $produtos->consultaVariavel('produtos', 'COUNT(*) as contagem', ['id_vendedor'], [$_SESSION['id']]);

		//paginacao
		if(isset($_GET['page']) && !empty($_GET['page'])) {

			$page = intval(htmlspecialchars($_GET['page'], ENT_QUOTES, 'UTF-8'));

		} else {

			$page = 1;

		}
        //LIMIT e OFFSET tem que jogar na pesquisa do banco de dados
		$limit = 10;
		$offset = ($page - 1) * $limit;

		$this->view->total_paginas = ceil($total_registros[0]['contagem'] / $limit);
		$this->view->pagina_atual = $page;
		$this->view->range_paginas = 2;

?>
<!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER--><!--NO CONTROLLER-->